use_frameworks!

target 'sinaDemo' do
    pod 'AutoInch'
    #    pod 'YYModel'
    #    pod 'AFNetworking', '~> 4.0'
    pod 'HandyJSON', '~> 5.0.2'
    pod 'Moya/RxSwift', '~> 14.0'
    pod 'SDWebImage'
    #下面是新手引导
    pod 'Instructions', '~> 2.0.1'
end


